name: MyMusicList Continuous Integration

on:
  - push
  - pull_request

jobs:
  lint_and_format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Check Code Format
        uses: borales/actions-yarn@v4
        with:
          cmd: fmt:check
      - name: Lint Code
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
